### PR TITLE
Add back-end foundation for measuring Pull Requests per Event

### PR DESCRIPTION
**Pull request by nahurst**
Setting up a github service to get pull requests and commits for events given a date range and a target repo.

### CODE REVIEW

**Comment by courte** [comment]
The cassettes will probably need updating, but otherwise :+1:

**Comment by DBNess** [comment]
:+1: :+1: :+1: :sunglasses:

**Comment by courte** [comment]
Thanks, @nahurst. You rule! :clap: :tada:

**Comment by nahurst** [comment]
Thanks @courte - really looking forward to seeing how you extend this!

**Pull request merged**
