### PR TITLE
Added "all projects" button to navigation bar and in-page navigation to event page

### PR DESCRIPTION
**Pull request by rachelmad**
screenshot 2015-02-28 14 20 59

Added the "All projects" button when mouse hovers over the Projects text. Leads to the same link as the Project button

### CODE REVIEW

**Comment by rachelmad** [comment]
screenshot 2015-02-28 16 34 03

Also added a sidebar in-page navigation to event show template using anchors and Foundation classes. Links only show up if the sections they lead to exist.

**Comment by courte** [comment]
@rachelmad - Great meeting you on Saturday! Thank you for making these changes :clap: :tada:

Because the in-page navigation is so design focused - and really not related to the previous work - I would like to review these changes as two separate pull requests (PRs). I'll take care of the "All Projects" work you did before the week is out, but I would love for you to make the in-page navigation PR yourself, if you have time, since you seemed so excited about git on Saturday.

If you're not interested in making this change, just comment and let me know. Otherwise, here's some deets on how to make it happen:

You'll want to:
 1. Make a new, appropriately-named branch off of master
 2. Use `git rebase -i` to remove the commit with the sha/id starting `3157223` on your new branch
 3. Push the new branch up to your forked remote
 4. Create a PR to `CodeMontageHQ:master` from `rachelmad:<NEW_BRANCH_NAME>`

Here's some details about `git rebase -i`: https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase-i. Using that tutorial, your `<base>` will be a commit sha before the one you want to change. Git rebase is powerful, but a bit confusing. Find some additional tutorials if you need them, or comment here with any specific questions.

Thanks again!!

**Comment by rachelmad** [comment]
Hi Courteney,

It was nice to meet you too!

I'd love to do this! I'll work on it one of these upcoming weekends :)

- Rachel

**Comment by courte** [comment]
@rachelmad - I thought I'd be able to separate out the first portion of this change (the "All Projects" link) without removing your name, but it looks like it's not going to be possible. I want you to get credit for your work, so I'd love it if you could now separate out both commits into separate branches and make new PRs for them.

The steps should be very similar to the ones I shared before, but for the other commit.

We'd love to have this fixed before an event we're hosting on 3/19, so if it's possible for you to work on it this weekend, that would be ideal. Otherwise, I'll split it up next Friday. (If that happens, you'll still have your name on the commit itself - no worries!)

**Comment by rachelmad** [comment]
@courte - Ok. I think I got it? Pull requests #360 #361. Thanks for the instructions too! I was trying to do that during coder day but I had no clue how to even start.

**Comment by courte** [comment]
@rachelmad - You rock! :clap: :clap: The new PRs look great. Thanks for getting to them over the weekend.

If you want to work on CodeMontage in the future, you will probably want to set your master branch back to upstream master using `git pull --force upstream master` or (if that doesn't work) `git rebase -i` again to remove the two additional commits.

Again, thank you! I'm looking forward to getting some of your code into the app.

**Comment by courte** [comment]
This has been split into #360 & #361, so I'll close it here.

**Pull request closed without merging**
