### PR TITLE
Fixed mission statement positioning for mobile.

### LINKED ISSUE #321: Fix mission statement on mobile devices
On mobile, the mission statement looks a bit oogly:
screenshot_2015-01-26-14-28-38

Adjusting the styling for smaller devices would be _awesome_!!

### PR DESCRIPTION
**Pull request by gbonfant**
Hello,

I came across this project from 24pullrequests and I'm quite eager to give a hand. I thought I'd start with something small such as this, it should fix #321. Here are the visual changes:

## Before
codemontage before

## After
codemontage after

### CODE REVIEW

**Comment by courte** [comment]
@gbonfant - thanks for this contribution! :clap: :clap:

I'm going to mark it for code review, and we'll let you know if we have any questions. Thanks again!

**Comment by courte** [comment]
I tried this locally, @gbonfant, and it looks great. I'm noticing that there's still about a 90px breakpoint (854px - 757px width). Would you mind adjusting for that?

After that change, it'll be ready to merge. :)

**Comment by gbonfant** [comment]
Thanks @courte. The latest commit should do it. It's an interesting edge case because in Foundation 3 that breakpoint falls into the large screen category.

**Comment by courte** [comment]
This is great, @gbonfant! :+1: We'll move it through our QA process as soon as possible. Thank you!

**Comment by DBNess** [comment]
Looks good! Thanks @gbonfant & @courte! :+1::+1::+1::sunglasses:

**Pull request merged**
