### PR TITLE
Modify the events page to show the rsvp before 'Join Us'

### PR DESCRIPTION
**Pull request by thefenry**
Issue #324 Modify the rsvp button so that it is positioned about Join us event phrase.

### CODE REVIEW

**Comment by courte** [comment]
@thefenry - this looks great! Would you please add a screenshot of the change? Once we have that, this change is :+1: for QA. :clap:

**Comment by thefenry** [comment]
Sorry @courte I posted the change in the issue page only. Here is the change. 


image

**Comment by courte** [comment]
Delish! Thanks, @thefenry! We'll start moving your changes through the QA process shortly. :)

**Comment by DBNess** [comment]
:+1::+1::+1::sunglasses:

**Comment by courte** [comment]
:tada: :fireworks: Thanks again, @thefenry!

**Pull request merged**
