### PR TITLE
Adding project requirements page, fixes #341.

### LINKED ISSUE #341: Create featured project requirements page
We currently do not have a page where we can post a list of what CodeMontage looks for in a featured project. This issue is hoping to resolve this by creating the follow:

- Our mission and how that is inline with our featured projects
- A list of requirements
- Link to contact information to become a featured project

### PR DESCRIPTION
**Pull request by juliaelman**
This also includes the addition of a link to this on the main nav. Not 100% sure that we want to do this or not, but will leave it up to the team to decide how to move forward.

I'd also like to see a link on `/projects` that references this page somehow. I started incorporating that on this PR, but then decided it was a bit out of scope. Let me know if you'd like me to open another issue with this specific addition. :space_invader: 

Also, let me know if you want screenshots too!

### CODE REVIEW

**Comment by DBNess** [comment]
@juliaelman :raised_hands: psyched to see this! Please include screenshots, too :+1:. Thank you kindly!

**Comment by juliaelman** [comment]
@DBNess below are screenshots of the entire page and of just the dropdown. Let me know if you need anything else! 

screen shot 2015-02-17 at 10 56 52 am

screen shot 2015-02-17 at 10 56 37 am

**Comment by DBNess** [comment]
Once this has a new line at the end of project_requirements file, it's ready to go! I'll create follow-up issues for improving the project navigation and other minor updates. Thanks so much, @juliaelman and @courte! :clap:

**Comment by juliaelman** [comment]
@DBNess done!

**Comment by DBNess** [comment]
:+1::+1::+1::sunglasses:

**Pull request merged**
