### PR TITLE
Navigation fixes

### PR DESCRIPTION
**Pull request by johnthepink**
Were you thinking more like this for the navigation spacing when logged out? I also found some responsive issues and fixed those as well.

**Logged Out Desktop**:

screenshot 2015-02-23 16 23 58

**Logged Out Mobile**:

screenshot 2015-02-23 16 24 04

**Logged Out Mobile Expanded**:

screenshot 2015-02-23 16 24 06

**Logged In Desktop**:

screenshot 2015-02-23 16 24 26

**Logged In Mobile**:

screenshot 2015-02-23 16 25 06

**Logged In Mobile Expanded**:

screenshot 2015-02-23 16 25 10

### CODE REVIEW

**Comment by courte** [comment]
Hey, @johnthepink - thanks for these changes! :confetti_ball: :tada: 

This definitely removes the margin issue, but it also makes a slight design change. With the existing code, the edge of the nav bar falls right below the word "montage" in the logo:
screenshot 2015-02-26 13 39 50

and in your screenshots the edge moved above the word "montage". Could you use a media query to ensure the margin only changes in the small version of the app? Thank you!

Additionally, before this is QA-ready, it would be great if you could make a few other changes:
 - Separate the fix for #289 from the responsive issues you fixed and submit a different PR for the latter, so it's easier to tell what changes were made for which reason.
 - Confirm that you're using [Foundation-style media queries](http://foundation.zurb.com/docs/v/4.3.2/media-queries.html) wherever possible.
 - Fix any HoundCI syntax errors.

Sorry to overwhelm with the adjustment asks. I appreciate you taking the time to try to fix this bug. Don't hesitate to let me know if you have any questions!

**Comment by johnthepink** [comment]
No worries! Thanks for the feedback. I'd love to make the changes you suggested, I'm just not sure I completely understand what you're going for. 

Are you saying you want the logged out nav to be the same as it currently is, and then fix the logged out mobile spacing issue? When I made the logged out top margin the same as the logged in, it didn't leave enough room for the logo to sit in the same place in relation to the end of the nav.

Sorry for the confusion :smile_cat:

**Comment by johnthepink** [comment]
@courte just realized you may not have seen my last comment since I didn't tag you.

**Comment by courte** [comment]
Sorry for the delay, @johnthepink! Yes - you're right on track. I'd like the logged out nav to stay the same, and then just fix the mobile spacing issue, which will probably require setting the margin change inside of a media query. :+1:

**Comment by johnthepink** [comment]
Ok awesome @courte. I will fix this up soon.

**Comment by johnthepink** [comment]
I'm going to close this and start over.

**Pull request closed without merging**
