### PR TITLE
back to top scroll small part css, js and top-icon image added

### PR DESCRIPTION
**Pull request by Thirumal-Sakthivel**
I added "back to top" functionality to this project and attached screen shot here.

screen-shot-for-back-to-top

### CODE REVIEW

**Comment by Thirumal-Sakthivel** [comment]
@DBNess! I have added foundation icon instead of top_icon.png for back to top scroll functionality.

**Comment by DBNess** [comment]
Awesome! Thanks, @Thirumal-Sakthivel -- can you please update the screenshot when you get the chance? Happy New Year! :tada:

**Comment by Thirumal-Sakthivel** [comment]
@DBNess! I have added screenshot. Happy New Year! 
back_to_top

**Comment by courte** [comment]
@Thirumal-Sakthivel,  I'm sorry for the delay on this, but thanks for this contribution! I was testing it on staging, and it works like a charm.

One quick note on the code: would it be possible for you to add a new line at the end of the files you changed? Once the new lines are added, this should be good-to-go and ready to merge into the app. Thank you!

(Again, sorry to ask you so long after you made the initial pull request. We've got Hound CI set up now to help us out with style notes like this, so it should be much easier & quicker in the future.)

**Comment by DBNess** [comment]
:clap:!

**Pull request merged**
